# Generated by Django 5.1.3 on 2026-01-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CajaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("monto_inicial", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monto_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id_cliente",
                    models.IntegerField(
                        db_column="id_cliente", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=100)),
                (
                    "apellido",
                    models.CharField(
                        blank=True, db_column="apellido", max_length=100, null=True
                    ),
                ),
                (
                    "correo",
                    models.CharField(
                        blank=True, db_column="correo", max_length=150, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_column="activo", default=True)),
                (
                    "esocasional",
                    models.BooleanField(db_column="EsOcasional", default=False),
                ),
            ],
            options={
                "db_table": "Clientes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Egresos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("concepto", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id_producto",
                    models.IntegerField(
                        db_column="Id_Producto", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(db_column="Nombre", max_length=100)),
                (
                    "precioventa",
                    models.DecimalField(
                        db_column="PrecioVenta", decimal_places=2, max_digits=10
                    ),
                ),
                ("cantidad", models.IntegerField(db_column="Cantidad", default=0)),
                (
                    "rutafoto",
                    models.ImageField(
                        blank=True,
                        db_column="rutaFoto",
                        null=True,
                        upload_to="productos/",
                    ),
                ),
                (
                    "stockminimo",
                    models.IntegerField(blank=True, db_column="StockMinimo", null=True),
                ),
                ("activo", models.BooleanField(db_column="Activo", default=True)),
            ],
            options={
                "db_table": "Productos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                (
                    "id_proveedor",
                    models.IntegerField(
                        db_column="id_Proveedor", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombre_proveedor",
                    models.CharField(db_column="nombre_proveedor", max_length=100),
                ),
                (
                    "correo",
                    models.CharField(
                        blank=True, db_column="correo", max_length=100, null=True
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, db_column="Direccion", null=True),
                ),
                ("activo", models.BooleanField(db_column="Activo", default=True)),
            ],
            options={
                "db_table": "Proveedores",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=100)),
                ("Correo", models.CharField(max_length=100, unique=True)),
                ("Contraseña", models.CharField(max_length=100)),
                ("Rol", models.CharField(max_length=50)),
                (
                    "token_recuperacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClienteTelefono",
            fields=[
                (
                    "id_telefonocli",
                    models.AutoField(
                        db_column="id_telefonoCli", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero_telefono_c",
                    models.CharField(db_column="numero_telefono_C", max_length=20),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tienda.clientes",
                    ),
                ),
            ],
            options={
                "db_table": "ClienteTelefono",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Facturas",
            fields=[
                ("id_factura", models.AutoField(primary_key=True, serialize=False)),
                ("FechaHora", models.DateTimeField(auto_now_add=True)),
                ("Total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "CostoEnvio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("anulada", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.clientes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cantidad", models.IntegerField()),
                ("Subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.facturas",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.productos",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productos",
            name="idproveedor",
            field=models.ForeignKey(
                blank=True,
                db_column="IdProveedor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tienda.proveedores",
            ),
        ),
        migrations.CreateModel(
            name="ProveedorProducto",
            fields=[
                (
                    "id_asignacion",
                    models.AutoField(
                        db_column="Id_Asignacion", primary_key=True, serialize=False
                    ),
                ),
                (
                    "preciocompra",
                    models.DecimalField(
                        db_column="PrecioCompra", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "cantidadcompra",
                    models.IntegerField(db_column="CantidadCompra", default=1),
                ),
                ("activo", models.BooleanField(db_column="Activo", default=True)),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="Id_Producto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tienda.productos",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        db_column="Id_Proveedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tienda.proveedores",
                    ),
                ),
            ],
            options={
                "db_table": "ProveedorProducto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProveedorTelefono",
            fields=[
                (
                    "id_telefonoprove",
                    models.AutoField(
                        db_column="id_telefonoProve", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero_telefono_p",
                    models.CharField(db_column="numero_telefono_P", max_length=20),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        db_column="id_Proveedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tienda.proveedores",
                    ),
                ),
            ],
            options={
                "db_table": "ProveedorTelefono",
                "managed": True,
            },
        ),
    ]
