# Generated by Django 5.2.7 on 2025-12-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(db_column='Id_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100, null=True)),
                ('precioventa', models.DecimalField(blank=True, db_column='PrecioVenta', decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('rutafoto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='rutaFoto', max_length=500, null=True)),
                ('stockminimo', models.IntegerField(blank=True, db_column='StockMinimo', null=True)),
                ('activo', models.BooleanField(db_column='Activo')),
                ('idproveedor', models.IntegerField(blank=True, db_column='IdProveedor', null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
    ]
