# Generated by Django 6.0.4 on 2026-06-13 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_frontal', models.ImageField(blank=True, null=True, upload_to='identidades/')),
                ('foto_trasera', models.ImageField(blank=True, null=True, upload_to='identidades/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identidad', to='tienda.clientes')),
            ],
            options={
                'db_table': 'ClienteIdentidad',
            },
        ),
    ]
