# Generated by Django 5.2.7 on 2025-12-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_Cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('esocasional', models.BooleanField(db_column='EsOcasional', default=False)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='Id_Proveedor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id_asignacion', models.AutoField(db_column='Id_Asignacion', primary_key=True, serialize=False)),
                ('preciocompra', models.DecimalField(db_column='PrecioCompra', decimal_places=2, max_digits=10)),
                ('cantidadcompra', models.IntegerField(db_column='CantidadCompra', default=1)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name_plural': 'Costos',
                'db_table': 'ProveedorProducto',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False, 'verbose_name_plural': 'Productos'},
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('Id_Factura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('Id_Detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='tienda.productos')),
                ('Factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='tienda.facturas')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'DetalleFactura',
                'managed': True,
            },
        ),
    ]
