# Generated by Django 5.1.3 on 2026-01-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturas",
            name="en_deuda",
            field=models.BooleanField(default=False),
        ),
    ]
