# Generated by Django 5.2.7 on 2026-04-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_facturas_en_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='arqueo_desglose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
