# Generated by Django 5.2.7 on 2025-12-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_clientes_proveedores_proveedorproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'managed': False, 'verbose_name_plural': 'Detalles de Factura'},
        ),
        migrations.AlterModelOptions(
            name='facturas',
            options={'managed': False, 'verbose_name_plural': 'Facturas'},
        ),
    ]
