# Generated by Django 6.0.4 on 2026-06-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_clienteidentidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionesPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('PERDIDA_LOCAL', 'Pérdida Interna (Daño en Local)'), ('DEV_CLIENTE', 'Devolución de Cliente (Intercambio)'), ('DEV_PROVEEDOR', 'Envío Directo a Proveedor (Vencidos)')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.TextField(help_text='Razón del daño o estado del producto')),
                ('estado_proveedor', models.CharField(choices=[('PENDIENTE', 'Pendiente de Reposición'), ('RESUELTO', 'Repuesto por Proveedor'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos', verbose_name='Producto afectado')),
            ],
        ),
    ]
