# Generated by Django 6.0.4 on 2026-05-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_detallefactura_options_alter_facturas_options'),
        ('tienda', '0003_cajadiaria_arqueo_desglose'),
    ]

    operations = [
    ]
